
# Credentials for the server
ServerCredentials:
  Host: "123.123.123.123"
  Port: "12345"
  Password: "password"

# Initial user interface state
UIStartupOptions:
  ScreenSize: 1000
  ShowPlayers: true
  ShowPlayerInfo: true
  ShowSpawns: false
  ShowTanks: true
  ShowGridOverlay: true
  ShowServerInfoOverlay: false
